#
resources:
  containers:
  - container: ubuntu
    image: 'ubuntu:16.04'
    options: --user 1001:117
    
    
stages:
- stage: Initialize
  jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-16.04'

      container: ubuntu

      steps:
        - script: printenv
