general:
steps:
  dockerExecute:
    dockerPullImage: true
    sidecarPullImage: true
    stashContent: []
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'ppiper/mta-archive-builder'
    dockerEnvVars: ['HOME':'/tmp/mta']
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    dockerImage: 'ppiper/cf-cli'
    dockerEnvVars: 'HOME=/tmp/piper'
    cloudFoundry:
      org: 'D046169trial_dev2'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
  neoDeploy:
    neo:
      account: 'd046169trial'
      credentialsId: 'CI_CREDENTIALS_ID'
