general:
  jenkinsKubernetes:
    # Setting security context globally is currently not working with jaas
    securityContext:
      runAsUser: 1000
      fsGroup: 1000

steps:
  dockerExecute:
    dockerPullImage: true
    sidecarPullImage: true
    stashContent: []
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'rstengel/mta-archive-builder'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    dockerImage: 'rstengel/cf-cli'
    cloudFoundry:
      org: 'pipertest'
      space: 'J333'
      credentialsId: 'CF_CREDENTIALSID'
  neoDeploy:
    neo:
      account: 'd046169trial'
      credentialsId: 'NEO_CREDENTIALS_ID'
