general:

steps:
  dockerExecute:
    dockerPullImage: true
    sidecarPullImage: true
    stashContent: []
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'devxci/mbtci-alpine'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    dockerImage: 'ppiper/cf-cli'
    cloudFoundry:
      org: 'pipertest'
      space: 'J333'
      credentialsId: 'CF_CREDENTIALSID'
  neoDeploy:
    neo:
      account: 'd046169trial'
      credentialsId: 'NEO_CREDENTIALS_ID'
