general:
 buildTool: 'mta'
 productiveBranch: 'master'
 gitUserName: 'd046169'
 gitUserEMail: 'r.stengel@sap.com'
 gitSshKeyCredentialsId: 'GIT_CREDENTIALS'
 
steps:
  dockerExecute:
    dockerPullImage: true
    sidecarPullImage: true
    stashContent: []
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'ppiper/mta-archive-builder'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    dockerImage: 'ppiper/cf-cli'
    cloudFoundry:
      org: 'pipertest'
      space: 'J333'
      credentialsId: 'CF_CREDENTIALSID'
  neoDeploy:
    neo:
      account: 'd046169trial'
      credentialsId: 'NEO_CREDENTIALS_ID'
