general:
steps:
  dockerExecute:
    dockerPullImage: true
    sidecarPullImage: true
    stashContent: []
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'pipertest'
      space: 'J333'
      credentialsId: 'CF_CREDENTIALSID'
