general:
  buildTool: 'mta'
  productiveBranch: 'master'
  gitUserName: 'd046169'
  gitUserEMail: 'r.stengel@sap.com'
  gitSshKeyCredentialsId: 'GIT_CREDENTIALS'
  verbose: true
  changeManagement:
    credentialsId: 'CM_CREDENTIALS_ID'
    solman:
      docker:
        image: 'rstengel/cm-client-sap-cert'
  
stages:
  Build:
    script: this
 
steps:
#  pipelineStashFilesBeforeBuild:
#    noDefaultExludes: []
  dockerExecute:
    dockerPullImage: true
    sidecarPullImage: true
#    stashContent: [] 
#  dockerExecuteOnKubernetes:
#    stashNoDefaultExcludes: true
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'ppiper/mta-archive-builder'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    dockerImage: 'ppiper/cf-cli'
    cloudFoundry:
      org: 'pipertest'
      space: 'J333'
      credentialsId: 'CF_CREDENTIALSID'
  transportRequestUploadSOLMAN:
    verbose: true
    dockerImage: 'rstengel/cm-client-sap-cert'
    stashNoDefaultExcludes: true
#    stashContent:
#      - 'git'
  transportRequestReqIDFromGit:
    verbose: true
    dockerImage: 'rstengel/cm-client-sap-cert'
    dockerOptions: []
    dockerEnvVars: {}
    dockerPullImage: true
    stashContent:
      - 'git'
