general:
  # Setting security context globally is currently not working with jaas
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
  jenkinsKubernetes:
    # Setting security context globally is currently not working with jaas
    securityContext:
      runAsUser: 1002
      fsGroup: 1002

steps:
  dockerExecute:
    dockerPullImage: true
    sidecarPullImage: true
    stashContent: []
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'ppiper/mta-archive-builder'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    dockerImage: 'ppiper/cf-cli'
    cloudFoundry:
      org: 'pipertest'
      space: 'J333'
      credentialsId: 'CF_CREDENTIALSID'
  neoDeploy:
    neo:
      account: 'd046169trial'
      credentialsId: 'NEO_CREDENTIALS_ID'
