general:
steps:
  dockerExecute:
    dockerPullImage: true
    sidecarPullImage: true
    stashContent: []
    dockerOptions: '-u root'
  mtaBuild:
    buildTarget: 'CF'
    dockerOptions: '-u 0'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'D046169trial_trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
